import { Geist, Geist_Mono, Inter, Poppins,Noto_Serif } from "next/font/google";
import "./globals.css";
import Sidebar from "./component/Sidebar";
import Topbar from "./component/Topbar";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["900", "800", "700", "600", "500"],
});

const noto = Noto_Serif({
  variable: "--font-noto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Drivest Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${poppins.variable} ${noto.variable} antialiased`}
      >
       
        <div className="flex h-screen overflow-hidden">
          
        
            <Sidebar />
         

         
          <div className="flex-1 flex flex-col min-w-0 min-h-0 ">
           
            <div>
              <Topbar />
            </div>

         
            <main className="flex-1 min-h-0 overflow-y-auto bg-[#CCDCE9] pt-6 pb-[50px] pl-6 pr-12 ">
            <div className="w-full max-w-full overflow-x-hidden ">
            {children}
            </div>
          </main>


          </div>
        </div>
      </body>
    </html>
  );
}
