import { Geist, Geist_Mono, Inter, Poppins,Noto_Serif } from "next/font/google";
import "./globals.css";
import Providers from "./providers";





const geistSans = Geist({ 
  variable: "--font-geist-sans", 
  subsets: ["latin"] });
  
const geistMono = Geist_Mono({ 
  variable: "--font-geist-mono", 
  subsets: ["latin"] });

const inter = Inter({ 
  variable: "--font-inter", 
  subsets: ["latin"] });

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["900", "800", "700", "600", "500"],
});

const noto = Noto_Serif({
  variable: "--font-noto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Drivest Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${poppins.variable} ${noto.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
